import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import './globals.css'

const NotoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'RWAM Portfolio',
  description: 'Generated by RWAM',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="ko">
      <body className={`${NotoSansKR.className} h-dvh w-dvw bg-slate-100`}>
        <div className="app bg-slate-200">
          <header className="header">
            <h1 className="title">
              김성주
              <span className="block">RWAMIN</span>
            </h1>
          </header>
          <nav className="menu">
            <ul className="menu-box"></ul>
          </nav>
          {children}
        </div>
      </body>
    </html>
  )
}
